[2025-03-27T02:30:00.832+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T02:30:00.841+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_session_data.ETL scheduled__2025-03-26T02:30:00+00:00 [queued]>
[2025-03-27T02:30:00.846+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_session_data.ETL scheduled__2025-03-26T02:30:00+00:00 [queued]>
[2025-03-27T02:30:00.846+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-03-27T02:30:00.855+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): ETL> on 2025-03-26 02:30:00+00:00
[2025-03-27T02:30:00.861+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3498) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-27T02:30:00.861+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_session_data', 'ETL', 'scheduled__2025-03-26T02:30:00+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/data226_hwk6_ETL.py', '--cfg-path', '/tmp/tmpdued6oln']
[2025-03-27T02:30:00.863+0000] {standard_task_runner.py:72} INFO - Started process 3501 to run task
[2025-03-27T02:30:00.863+0000] {standard_task_runner.py:105} INFO - Job 73: Subtask ETL
[2025-03-27T02:30:00.893+0000] {task_command.py:467} INFO - Running <TaskInstance: user_session_data.ETL scheduled__2025-03-26T02:30:00+00:00 [running]> on host ef75a37f18d3
[2025-03-27T02:30:00.941+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_session_data' AIRFLOW_CTX_TASK_ID='ETL' AIRFLOW_CTX_EXECUTION_DATE='2025-03-26T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-26T02:30:00+00:00'
[2025-03-27T02:30:00.942+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-27T02:30:00.951+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn2'
[2025-03-27T02:30:00.952+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-27T02:30:00.952+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-27T02:30:00.953+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-27T02:30:01.643+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-27T02:30:01.735+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-27T02:30:01.860+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-27T02:30:02.082+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-27T02:30:03.313+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-27T02:30:04.073+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-27T02:30:04.212+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-27T02:30:04.212+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-27T02:30:04.219+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-27T02:30:04.219+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=user_session_data, task_id=ETL, run_id=scheduled__2025-03-26T02:30:00+00:00, execution_date=20250326T023000, start_date=20250327T023000, end_date=20250327T023004
[2025-03-27T02:30:04.246+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-27T02:30:04.256+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-27T02:30:04.259+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
