[2025-03-05T06:32:37.530+0000] {processor.py:186} INFO - Started process (PID=236) to work on /opt/airflow/dags/data226_hwk5 (4).py
[2025-03-05T06:32:37.531+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (4).py for tasks to queue
[2025-03-05T06:32:37.532+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:32:37.532+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (4).py
[2025-03-05T06:32:37.546+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:32:37.542+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (4).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (4).py", line 123, in <module>
    url = f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={symbol}&apikey={api_key}'
                                                                                                 ^^^^^^^
NameError: name 'api_key' is not defined
[2025-03-05T06:32:37.548+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (4).py
[2025-03-05T06:32:37.561+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (4).py took 0.035 seconds
[2025-03-05T06:33:08.231+0000] {processor.py:186} INFO - Started process (PID=289) to work on /opt/airflow/dags/data226_hwk5 (4).py
[2025-03-05T06:33:08.231+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (4).py for tasks to queue
[2025-03-05T06:33:08.233+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:33:08.232+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (4).py
[2025-03-05T06:33:08.245+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:33:08.242+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (4).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (4).py", line 123, in <module>
    url = f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={symbol}&apikey={api_key}'
                                                                                                 ^^^^^^^
NameError: name 'api_key' is not defined
[2025-03-05T06:33:08.247+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (4).py
[2025-03-05T06:33:08.259+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (4).py took 0.031 seconds
